version: '3'

services:
  backend:
    build:
      context: .
      args:
        env: dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - traum-kaffee
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.3-alpine3.20
    platform: linux/amd64
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - traum-kaffee-volume:/var/lib/postgresql/data

volumes:
  traum-kaffee-volume:
    driver: local

networks:
  traum-kaffee: